package org.example;

public enum Genre {
    Action,
    Adventure,
    Comedy,
    Drama,
    Horror,
    SF,
    Fantasy,
    Romance,
    Mystery,
    Thriller,
    Crime,
    Biography,
    War,
    Cooking,
    ANIMATION,
    DOCUMENTARY,
    FAMILY,
    MUSIC,
    HISTORY,
    SPORT,
    WESTERN,
    SUPERHERO,
    MUSICAL,
    CRIME_DRAMA,
    ROMANTIC_COMEDY,
    FILM_NOIR,
    SUPERNATURAL,
    HISTORICAL,
    PSYCHOLOGICAL,
    SUSPENSE,
    ESPIONAGE,
    MOCKUMENTARY,
    COURTROOM_DRAMA,
    HORROR_COMEDY,
    CYBERPUNK,
    STEAMPUNK,
    NEO_NOIR,
    JAPANESE_ANIME,
    SATIRE,
    BLACK_COMEDY,
    FAMILY_DRAMA

}
